Remove-Item Env:CURRENT_USER_ID -ErrorAction SilentlyContinue
Remove-Item Env:LLM_PROVIDER -ErrorAction SilentlyContinue
Remove-Item Env:OL_MODE -ErrorAction SilentlyContinue
Remove-Item Env:OL_BASE_URL -ErrorAction SilentlyContinue
Remove-Item Env:OL_MODEL -ErrorAction SilentlyContinue
Remove-Item Env:OL_LOCAL_BASE_URL -ErrorAction SilentlyContinue
Remove-Item Env:OL_LOCAL_MODEL -ErrorAction SilentlyContinue
Remove-Item Env:OL_CLOUD_BASE_URL -ErrorAction SilentlyContinue
Remove-Item Env:OL_CLOUD_MODEL -ErrorAction SilentlyContinue
Remove-Item Env:OL_API_KEY -ErrorAction SilentlyContinue